### ISSUE TITLE
GSOC2019 - Continue development of wmc

### ISSUE THREAD

**Issue by Davide95** [internetarchive/wayback-machine-chrome#290]
Hi, I'm writing here because I sent an email to iagsoc2019@gmail.com 2 weeks ago and it seems that nobody will read it, so I'll post it here.

This year I would like to apply for GSOC and I saw an interesting project in your ideas list (Continue development of the Chrome extension “Wayback Machine).

My name is Davide, I’m an MSc student of Computer Science and I’ve a BSc in Computer Science.
If you want to know more about me:
-    https://www.linkedin.com/in/driva95/ 
-    https://github.com/Davide95 

My questions are:
- can I have more information about the project?
- what can I do to be prepared before the “student application period”?

Thanks in advance.

**Comment by hereisdx** [comment]
Hi!
My name is Divyanshu Agrawal, and I, too, wish to work on this project for GSoC 2019. I am an undergraduate student in Computer Science at BITS-Pilani, Hyderabad Campus, India.

It would be great if I could communicate with the members of The Internet Archive development team to get some additional information about this project, as the Google Doc for the Ideas does not contain any information about IRC Channels or otherwise!

Cheers!

**Comment by iamzubin** [comment]
I don't think mentors are right now active for this organization.
