### ISSUE TITLE
Option for auto-saving old bookmarks

### ISSUE THREAD

**Issue by weirdalsuperfan** [internetarchive/wayback-machine-chrome#595]
I'm really excited to have an extension like this. The first thing that I did after installing it and enabling the auto-save feature was manually reopen about 1000 different webpages I've bookmarked over time. Unfortunately, maybe 5% of them were dead with no backup on the wayback machine. The auto-save feature is the greatest thing ever, and should avoid me ever having this problem again. However, for people who have recently installed the extension, going through every single past bookmark, while a valuable exercise (if a little late for the dead webpages), takes an insanely long time. I haven't even gone through all of mine (I've given up at this point). 

An option to automatically index all of your bookmarks, and maybe one for indexing all of your currently open tabs (or does this work on all open tabs/immediately on opening a page...?), would be a huge time saver and would double the value of this extension in my eyes, since your bookmarks are the pages you most want saved (although it may be too late for some of them).

**Comment by cgorringe** [comment]
I'm glad that the auto-save feature helped! The idea to save past bookmarks is a really good idea that I hadn't thought of, thanks for suggesting it! And I think it's something we can do.

**Comment by cgorringe** [comment]
Adding some API links for future reference:

**Bookmarks API**
- https://developer.chrome.com/extensions/bookmarks
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks

**Comment by cgorringe** [comment]
**Some Brainstorming on the UI:**
- I was thinking we can call this the "Bulk Save" feature, which can include Bookmarks or any other list of URLs.
- We'd have a new window pop up (like the Resource List).
- It can contain 2 list boxes of URLs, the first is an editable text box of URLs that you'd like to Save. (input box)
- There's a button "Import All Bookmarks" that will populate the first list with all the URLs from traversing the Bookmarks tree structure.
- May want to store this list in a Set to avoid or otherwise check for duplicates.
- User can add additional URLs, or delete URLs from the list prior to hitting Save, in order to preserve Privacy in the case where the user doesn't want some URLs to be recorded.
- "Bulk Save" button starts the process.
- There's an animated spinner and a counter, or there could be a progress meter.
- SPN2 API supports saving upto 5 concurrent URLs at one time.
- The 2nd box displays the list of URLs as they are completed. (output box)
- Could show the 5 URLs currently being saved in a separate area, or maybe highlight them specially in the output or input boxes.
- Could provide checkbox Saving Options:
  - Save only URLs that have never been saved. (involves calling Availability API on each URL.)
  - Save URLs that haven't been saved since X date, or within past X days. (use timestamp provided by Availability API.)

**Comment by cgorringe** [comment]
Or it could be a single list box of URLs, which is initially editable, then no longer editable when user hits "Bulk Save". The URLs are then highlighted and marked with (let's say) checkboxes as each Save completes.

**Comment by weirdalsuperfan** [comment]
It all sounds good to me haha. As a user my main want would be the ability to select/deselect groups of bookmarks at the folder level from the tree, but I think it sounds like that's included already. I also really like the last two bullet points involving using the Availability API.
